import React, { useState } from 'react';
import { 
  BookOpen, 
  Droplet, 
  Gauge, 
  Library, 
  MessageSquare, 
  Wrench, 
  PenTool,
  CheckCircle2,
  XCircle,
  HelpCircle,
  ChevronDown
} from 'lucide-react';

// --- Components for layout and styling ---

const SectionHeading = ({ icon: Icon, title, id }) => (
  <h2 id={id} className="flex items-center gap-3 text-2xl font-bold text-slate-800 mt-12 mb-6 pb-2 border-b-2 border-indigo-100 scroll-mt-24">
    <div className="p-2 bg-indigo-100 text-indigo-600 rounded-lg">
      <Icon size={24} />
    </div>
    {title}
  </h2>
);

const SubHeading = ({ title }) => (
  <h3 className="text-xl font-semibold text-slate-700 mt-8 mb-4">{title}</h3>
);

const TermCard = ({ term, definition }) => (
  <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow">
    <h4 className="text-lg font-bold text-indigo-700 mb-2">{term}</h4>
    <p className="text-slate-600 mb-3">{definition}</p>
   
  </div>
);

// --- Interactive Exercise Components ---

const Exercise1 = () => {
  const [answers, setAnswers] = useState({ q1: '', q2: '', q3: '', q4: '' });
  const [submitted, setSubmitted] = useState(false);

  const correctAnswers = { q1: 'b', q2: 'd', q3: 'a', q4: 'c' };
  
  const options = [
    { value: 'a', text: 'a. Pressure measured relative to a vacuum' },
    { value: 'b', text: 'b. Force acting on an area' },
    { value: 'c', text: 'c. Pressure generated by liquid at rest' },
    { value: 'd', text: 'd. Pressure measured relative to atmospheric pressure' }
  ];

  const terms = [
    { id: 'q1', text: '1. Pressure' },
    { id: 'q2', text: '2. Gauge pressure' },
    { id: 'q3', text: '3. Absolute pressure' },
    { id: 'q4', text: '4. Hydrostatic pressure' },
  ];

  const checkAnswers = () => setSubmitted(true);
  const reset = () => { setAnswers({ q1: '', q2: '', q3: '', q4: '' }); setSubmitted(false); };

  return (
    <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 mb-8">
      <h4 className="font-bold text-lg mb-4">Exercise 1: Vocabulary Matching</h4>
      <p className="text-slate-600 mb-4 text-sm">Match the term to the correct definition.</p>
      
      <div className="grid md:grid-cols-2 gap-8 mb-6">
        <div className="space-y-4">
          {terms.map(term => (
            <div key={term.id} className="flex items-center gap-3">
              <span className="w-48 font-medium text-slate-700">{term.text}</span>
              <select 
                disabled={submitted}
                className={`p-2 border rounded-lg flex-1 outline-none focus:ring-2 focus:ring-indigo-500 ${submitted ? (answers[term.id] === correctAnswers[term.id] ? 'bg-green-50 border-green-300' : 'bg-red-50 border-red-300') : 'bg-white'}`}
                value={answers[term.id]}
                onChange={(e) => setAnswers({...answers, [term.id]: e.target.value})}
              >
                <option value="">Select...</option>
                <option value="a">a</option>
                <option value="b">b</option>
                <option value="c">c</option>
                <option value="d">d</option>
              </select>
              {submitted && (
                answers[term.id] === correctAnswers[term.id] 
                  ? <CheckCircle2 className="text-green-500" size={20} />
                  : <XCircle className="text-red-500" size={20} />
              )}
            </div>
          ))}
        </div>
        <div className="bg-white p-4 rounded-lg border border-slate-200 space-y-3">
          {options.map(opt => (
            <div key={opt.value} className="text-sm text-slate-700">{opt.text}</div>
          ))}
        </div>
      </div>
      
      <div className="flex gap-3">
        <button onClick={checkAnswers} disabled={submitted} className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors disabled:opacity-50 font-medium">
          Check Answers
        </button>
        {submitted && (
          <button onClick={reset} className="px-4 py-2 bg-slate-200 text-slate-700 rounded-lg hover:bg-slate-300 transition-colors font-medium">
            Retry
          </button>
        )}
      </div>
    </div>
  );
};

const Exercise2 = () => {
  const [answers, setAnswers] = useState({ q1: '', q2: '', q3: '' });
  const [submitted, setSubmitted] = useState(false);

  const correctAnswers = { 
    q1: ['pascal', 'pa'], 
    q2: ['zero', '0', 'zero pascals', '0 pascals', '0 pa'], 
    q3: ['hydrostatic'] 
  };

  const isCorrect = (id, val) => correctAnswers[id].includes(val.trim().toLowerCase());

  const checkAnswers = () => setSubmitted(true);
  const reset = () => { setAnswers({ q1: '', q2: '', q3: '' }); setSubmitted(false); };

  const sentences = [
    { id: 'q1', prefix: '1. The SI unit of pressure is the ', suffix: '.' },
    { id: 'q2', prefix: '2. Atmospheric pressure is assumed to be ', suffix: ' when calculating gauge pressure.' },
    { id: 'q3', prefix: '3. Pressure generated by water due to its height is called ', suffix: ' pressure.' }
  ];

  return (
    <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 mb-8">
      <h4 className="font-bold text-lg mb-4">Exercise 2: Sentence Completion</h4>
      <p className="text-slate-600 mb-4 text-sm">Complete the sentences using correct technical terms.</p>
      
      <div className="space-y-4 mb-6">
        {sentences.map(s => (
          <div key={s.id} className="flex flex-wrap items-center gap-2 text-slate-700">
            <span>{s.prefix}</span>
            <div className="relative">
              <input 
                type="text"
                disabled={submitted}
                value={answers[s.id]}
                onChange={(e) => setAnswers({...answers, [s.id]: e.target.value})}
                className={`w-32 p-1 px-2 border-b-2 bg-transparent outline-none focus:border-indigo-500 font-semibold text-indigo-700 ${submitted ? (isCorrect(s.id, answers[s.id]) ? 'border-green-500 text-green-700' : 'border-red-500 text-red-700') : 'border-slate-300'}`}
              />
              {submitted && isCorrect(s.id, answers[s.id]) && <CheckCircle2 className="absolute -right-6 top-1.5 text-green-500" size={16} />}
              {submitted && !isCorrect(s.id, answers[s.id]) && <XCircle className="absolute -right-6 top-1.5 text-red-500" size={16} />}
            </div>
            <span>{s.suffix}</span>
          </div>
        ))}
      </div>

      <div className="flex gap-3">
        <button onClick={checkAnswers} disabled={submitted} className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors disabled:opacity-50 font-medium">
          Check Answers
        </button>
        {submitted && (
          <button onClick={reset} className="px-4 py-2 bg-slate-200 text-slate-700 rounded-lg hover:bg-slate-300 transition-colors font-medium">
            Retry
          </button>
        )}
      </div>
    </div>
  );
};

const Exercise3 = () => {
  const [showAnswers, setShowAnswers] = useState([false, false, false]);

  const toggleAnswer = (index) => {
    const newAnswers = [...showAnswers];
    newAnswers[index] = !newAnswers[index];
    setShowAnswers(newAnswers);
  };

  const questions = [
    {
      q: "1. Explain the difference between gauge pressure and absolute pressure.",
      a: "Gauge pressure is measured relative to atmospheric pressure (where atmospheric pressure is assumed to be zero). Absolute pressure is measured relative to a perfect vacuum (where pressure is truly zero)."
    },
  ];

  return (
    <div className="bg-slate-50 p-6 rounded-xl border border-slate-200">
      <h4 className="font-bold text-lg mb-4">Exercise 3: Engineering Application</h4>
      <p className="text-slate-600 mb-6 text-sm">Answer in complete sentences. Click "Show Example Answer" to check your understanding.</p>
      
      <div className="space-y-6">
        {questions.map((item, idx) => (
          <div key={idx} className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm">
            <p className="font-medium text-slate-800 mb-3">{item.q}</p>
            <textarea 
              className="w-full p-3 border border-slate-200 rounded-lg mb-3 outline-none focus:ring-2 focus:ring-indigo-500 text-slate-700" 
              rows="3" 
              placeholder="Type your answer here..."
            ></textarea>
            
            <button 
              onClick={() => toggleAnswer(idx)}
              className="flex items-center gap-2 text-indigo-600 font-medium text-sm hover:text-indigo-800 transition-colors"
            >
              <HelpCircle size={16} />
              {showAnswers[idx] ? 'Hide Example Answer' : 'Show Example Answer'}
            </button>
            
            {showAnswers[idx] && (
              <div className="mt-3 p-3 bg-indigo-50 text-indigo-900 border-l-4 border-indigo-500 rounded-r-lg text-sm leading-relaxed">
                <strong>Example Answer:</strong> {item.a}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

// --- Main Application Component ---

export default function App() {
  const sections = [
    { id: 'overview', title: '1. Overview', icon: BookOpen },
    { id: 'vocabulary', title: '2. Key Vocabulary', icon: Library },
    { id: 'gauge-absolute', title: '3. Gauge vs Absolute', icon: Gauge },
    { id: 'grammar', title: '4. Grammar Focus', icon: MessageSquare },
    { id: 'hydrostatic', title: '5. Hydrostatic Pressure', icon: Droplet },
    { id: 'examples', title: '6. Practical Examples', icon: Wrench },
    { id: 'exercises', title: '7. Exercises', icon: PenTool },
  ];

  return (
    <div className="min-h-screen bg-white font-sans text-slate-800 selection:bg-indigo-100 selection:text-indigo-900">
      {/* Header */}
      <header className="bg-indigo-900 text-white top-0 z-50 shadow-md">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold tracking-tight">Fluid Pressure</h1>
          </div>
        </div>
      </header>

      <div className="max-w-6xl mx-auto px-6 py-8 flex flex-col lg:flex-row gap-12">
        

        {/* Main Content Area */}
        <main className="lg:w-3/4 max-w-3xl">
          
          {/* Section 1: Overview */}
          <section id="overview">
            <SectionHeading icon={BookOpen} title="1. Overview of the Topic" id="overview" />
            <p className="text-lg text-slate-700 leading-relaxed bg-indigo-50/50 p-6 rounded-xl border border-indigo-100">
              This lesson explains fluid pressure, focusing on the difference between gauge pressure and absolute pressure, the units used to measure pressure, and how hydrostatic pressure is generated in liquids. The language reflects how pressure is described and calculated in mechanical, civil, and process engineering.
            </p>
          </section>

          {/* Section 2: Key Technical Vocabulary */}
          <section id="vocabulary">
            <SectionHeading icon={Library} title="2. Key Technical Vocabulary" id="vocabulary" />
            
            <SubHeading title="2.1 Pressure" />
            <div className="mb-6">
              <TermCard 
                term="Pressure" 
                definition="The amount of force acting on an area." 
              />
              <p className="mt-4 text-slate-700">Fluids (liquids and gases) exert pressure on the surfaces that contain them, such as <strong>tanks</strong>, <strong>pipes</strong>, and <strong>hoses</strong>.</p>
              
              <div className="mt-4 grid sm:grid-cols-3 gap-4">
                <div className="bg-blue-50 p-4 rounded-lg border border-blue-100 flex flex-col items-center text-center">
                  <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center mb-3 text-blue-600">
                    <Gauge size={24} />
                  </div>
                  <span className="text-sm font-medium text-blue-900">Compressed air in hoses</span>
                </div>
                <div className="bg-orange-50 p-4 rounded-lg border border-orange-100 flex flex-col items-center text-center">
                  <div className="w-12 h-12 bg-orange-100 rounded-full flex items-center justify-center mb-3 text-orange-600">
                    <Droplet size={24} />
                  </div>
                  <span className="text-sm font-medium text-orange-900">Compressed gas (propane) in cylinders</span>
                </div>
                <div className="bg-cyan-50 p-4 rounded-lg border border-cyan-100 flex flex-col items-center text-center">
                  <div className="w-12 h-12 bg-cyan-100 rounded-full flex items-center justify-center mb-3 text-cyan-600">
                    <Droplet size={24} fill="currentColor" />
                  </div>
                  <span className="text-sm font-medium text-cyan-900">Water in water mains</span>
                </div>
              </div>
            </div>

            <SubHeading title="2.2 Units of Pressure" />
            <div className="grid sm:grid-cols-2 gap-4">
              <TermCard 
                term="Pascal (Pa)" 
                definition="The SI unit of pressure."
              />
              <TermCard 
                term="Bar" 
                definition="Another common unit of pressure."
              />
              <div className="sm:col-span-2">
                <TermCard 
                  term="Atmospheric pressure" 
                  definition="The pressure of the air in the atmosphere at sea level."
                />
              </div>
            </div>
          </section>

          {/* Section 3: Gauge vs Absolute */}
          <section id="gauge-absolute">
            <SectionHeading icon={Gauge} title="3. Gauge Pressure and Absolute Pressure" id="gauge-absolute" />
            
            <div className="space-y-8">
              {/* 3.1 Gauge */}
              <div>
                <SubHeading title="3.1 Gauge Pressure" />
                <div className="bg-white border-l-4 border-indigo-500 p-5 rounded-r-xl shadow-sm mb-4">
                  <p className="font-medium text-slate-800 mb-2">Gauge pressure is the pressure difference between:</p>
                  <ul className="list-disc list-inside text-slate-700 mb-4 ml-2">
                    <li>The fluid inside a vessel</li>
                    <li>The atmospheric pressure outside the vessel</li>
                  </ul>
                  <p className="text-sm bg-indigo-50 text-indigo-800 p-3 rounded-lg inline-block font-medium">
                    When using gauge pressure, atmospheric pressure is assumed to be zero Pascals.
                  </p>
                </div>
                
                <div className="bg-slate-50 p-5 rounded-xl border border-slate-200">
                  <h4 className="font-bold text-slate-800 mb-3 flex items-center gap-2">
                    <Wrench size={18} className="text-slate-500" /> 
                    Why engineers use gauge pressure:
                  </h4>
                  <p className="text-slate-700 mb-2">To determine whether pressure inside a vessel is higher or lower than outside (and by how much).</p>
                  <p className="text-slate-700 mb-2">This helps engineers design tanks and pipes so they:</p>
                  <ul className="grid sm:grid-cols-2 gap-3 mt-3">
                    <li className="bg-white p-3 rounded-lg border border-red-100 flex items-center gap-3">
                      <XCircle className="text-red-500 shrink-0" size={20} />
                      <span className="text-sm">Do not <strong>explode</strong><br/><span className="text-slate-500 text-xs">(positive gauge pressure)</span></span>
                    </li>
                    <li className="bg-white p-3 rounded-lg border border-purple-100 flex items-center gap-3">
                      <XCircle className="text-purple-500 shrink-0" size={20} />
                      <span className="text-sm">Do not <strong>implode</strong><br/><span className="text-slate-500 text-xs">(negative gauge pressure)</span></span>
                    </li>
                  </ul>
                </div>
              </div>

              {/* 3.2 Absolute */}
              <div>
                <SubHeading title="3.2 Absolute Pressure" />
                <div className="grid sm:grid-cols-2 gap-4">
                  <TermCard 
                    term="Absolute pressure" 
                    definition="Pressure measured relative to a perfect vacuum (zero pressure)."
                  />
                  <TermCard 
                    term="Vacuum" 
                    definition="A void containing no gas or liquid."
                  />
                </div>
              </div>

              {/* 3.3 Partial Vacuum */}
              <div>
                <SubHeading title="3.3 Partial Vacuum" />
                <div className="bg-slate-800 text-white p-6 rounded-xl relative overflow-hidden">
                  <div className="relative z-10">
                    <h4 className="text-lg font-bold mb-2">Partial vacuum</h4>
                    <p className="text-slate-300 mb-4">A pressure below atmospheric pressure, but not zero.</p>
                    <div className="bg-slate-700/50 p-4 rounded-lg border border-slate-600">
                      <strong className="text-amber-400 block mb-2 text-sm uppercase tracking-wide">Important Comparison:</strong>
                      <ul className="space-y-2 text-sm">
                        <li className="flex items-center gap-2">
                          <CheckCircle2 size={16} className="text-green-400" />
                          Has <strong>positive pressure</strong> when measured as absolute pressure
                        </li>
                        <li className="flex items-center gap-2">
                          <CheckCircle2 size={16} className="text-green-400" />
                          Has <strong>negative pressure</strong> when measured as gauge pressure
                        </li>
                      </ul>
                    </div>
                  </div>
                  {/* Decorative background element */}
                  <div className="absolute -right-12 -bottom-12 opacity-10">
                    <Gauge size={160} />
                  </div>
                </div>
              </div>
            </div>
          </section>

        

          {/* Section 5: Hydrostatic Pressure */}
          <section id="hydrostatic">
            <SectionHeading icon={Droplet} title="4. Hydrostatic Pressure and Siphonic Action" id="hydrostatic" />
            
            <SubHeading title="5.1 Hydrostatic Pressure" />
            <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm mb-6 flex gap-4 items-start">
              <div className="p-3 bg-blue-100 text-blue-600 rounded-lg shrink-0">
                <Droplet size={24} fill="currentColor" />
              </div>
              <div>
                <p className="text-slate-700 font-medium mb-1">Pressure generated by a liquid at rest.</p>
                <p className="text-slate-500 text-sm mb-3">Most commonly discussed in relation to water.</p>
                <div className="inline-block bg-blue-50 text-blue-800 px-3 py-1.5 rounded-md text-sm font-bold border border-blue-200">
                  Key Principle: Pressure increases with height of the liquid.
                </div>
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <SubHeading title="5.2 Head of Water" />
                <TermCard 
                  term="Head of water" 
                  definition="The height of a column of water. This height creates pressure at lower levels."
                />
                <div className="mt-4 bg-slate-50 p-4 rounded-lg border border-slate-200">
                  <h5 className="font-bold text-sm text-slate-800 mb-2">Example: Water Tower</h5>
                  <ol className="list-decimal list-inside text-sm text-slate-700 space-y-1">
                    <li>Stores water at a high level</li>
                    <li>The water pushes down</li>
                    <li>This puts water mains under pressure</li>
                  </ol>
                  <p className="mt-3 text-xs font-bold text-indigo-700 bg-indigo-50 p-2 rounded">
                    Important: Increasing the height of the water tower increases pressure at low level.
                  </p>
                </div>
              </div>
              
              <div>
                <SubHeading title="5.3 Header Tanks" />
                <TermCard 
                  term="Header tank" 
                  definition="A small tank located at a high level used to generate hydrostatic pressure."
                />
              </div>
            </div>
          </section>

          {/* Section 6: Practical Examples */}
          <section id="examples">
            <SectionHeading icon={Wrench} title="5. Practical Engineering Examples" id="examples" />
            <p className="text-slate-500 text-sm mb-4 italic">(These examples clarify the source text without adding new technical claims.)</p>
            
            <ul className="space-y-3">
              {[
                "Compressed air in a hose exerts pressure on the hose walls.",
                "Water mains are pressurized to deliver water to buildings.",
                "Gauge pressure indicates whether internal pressure is above or below atmospheric pressure.",
                "Water towers supply pressure using hydrostatic head.",
                "Header tanks provide pressure in multi-storey buildings."
              ].map((example, idx) => (
                <li key={idx} className="flex items-start gap-3 bg-white p-4 rounded-lg shadow-sm border border-slate-100">
                  <CheckCircle2 className="text-green-500 shrink-0 mt-0.5" size={20} />
                  <span className="text-slate-700">{example}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* Section 7: Exercises */}
          <section id="exercises">
            <SectionHeading icon={PenTool} title="6. Exercises" id="exercises" />
            <p className="text-slate-600 mb-8">Test your knowledge with the interactive exercises below.</p>
            
            <Exercise1 />
            <Exercise2 />
            <Exercise3 />
          </section>

        </main>
      </div>
   
    </div>
  );
}